name: Build Python App

on:
  push:
    branches: ["master", "main", "demo"]
    paths-ignore: ["dist/**"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:9
    if: github.actor != 'github-actions'

    steps:
      - name: Install dependencies for Rocky Linux 9
        run: |
          dnf install -y python3.11 python3.11-pip git gcc zlib-devel

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python3.11 -m pip install --upgrade pip
          python3.11 -m pip install -r requirements.txt

      - name: Build using PyInstaller
        run: |
          python3.11 -m pip install pyinstaller
          python3.11 -m PyInstaller --onefile --name agile_acp_tool \
            --add-data "app/static:app/static" \
            --add-data "app/demo_logs:app/demo_logs" \
            run.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: agile_acp_tool
          path: dist/agile_acp_tool

      - name: Configure git safe directory
        run: |
          git config --global --add safe.directory /__w/agile_config_tool/agile_config_tool

      - name: Commit built binary
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Add updated built binary"
          add: "-f dist/agile_acp_tool"
